"""empty message

Revision ID: 034d01a08271
Revises: 29cbd7c712fd
Create Date: 2020-04-08 17:58:44.314809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034d01a08271'
down_revision = '29cbd7c712fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('State',
    sa.Column('title', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['state'], ['State.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'state')
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('City')
    op.drop_table('State')
    # ### end Alembic commands ###
