"""empty message

Revision ID: 403250edf1de
Revises: e66d49f268f4
Create Date: 2020-04-08 19:31:21.850994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403250edf1de'
down_revision = 'e66d49f268f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'City', ['city_id'], ['id'])
    op.add_column('Venue', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'City', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'city_id')
    # ### end Alembic commands ###
