"""empty message

Revision ID: 52ebeafbc19d
Revises: 034d01a08271
Create Date: 2020-04-08 17:59:05.114855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ebeafbc19d'
down_revision = '034d01a08271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'City', ['city'], ['id'])
    op.add_column('Venue', sa.Column('city', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'City', ['city'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'city')
    # ### end Alembic commands ###
