"""empty message

Revision ID: 702dcd8bad2a
Revises: 403250edf1de
Create Date: 2020-04-08 19:35:42.365219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702dcd8bad2a'
down_revision = '403250edf1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
