"""empty message

Revision ID: 7331ecb6d08d
Revises: 8f4096ff1a55
Create Date: 2020-04-09 18:37:38.861164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7331ecb6d08d'
down_revision = '8f4096ff1a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
