"""empty message

Revision ID: b2a0a9014c07
Revises: cd7cd1b149d2
Create Date: 2020-04-09 18:52:29.228547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a0a9014c07'
down_revision = 'cd7cd1b149d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
