"""empty message

Revision ID: e66d49f268f4
Revises: af0c4cae1c91
Create Date: 2020-04-08 19:29:40.450733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66d49f268f4'
down_revision = 'af0c4cae1c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
